version: '3.6'

services:

  webserver:
    image: nginx:stable-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./html:/var/www/html
      - htpass:/etc/apache2:ro
    depends_on:
      - authentification

  authentification:
    image: apache2-utils:v3
    volumes:
      - htpass:/etc/apache2

volumes:
    htpass:
